version: "3"

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    # facilitate communication between containers
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
